# Part 1

## Preprocessing

In [1]:
!pip3 install dgl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 28.0 MB/s eta 0:00:00


In [2]:
!pip install dglgo

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 958.2 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 5.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 12.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.4/29.4 MB 27.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 51.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 32.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.7/572.7 kB 17.4 MB/s eta 0:00:00
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.wh

----------------------------------

In [3]:
%matplotlib inline
import os

os.environ["DGLBACKEND"] = "pytorch"
import dgl
import numpy as np
import networkx as nx
import torch
import torch.nn as nn

## defining graph




In [4]:
g = dgl.graph(([0, 0, 0, 0, 0], [1, 2, 3, 4, 5]), num_nodes=6)
# Equivalently, PyTorch LongTensors also work.
g = dgl.graph(
    (torch.LongTensor([0, 0, 0, 0, 0]), torch.LongTensor([1, 2, 3, 4, 5])),
    num_nodes=6,
)

# You can omit the number of nodes argument if you can tell the number of nodes from the edge list alone.
g = dgl.graph(([0, 0, 0, 0, 0], [1, 2, 3, 4, 5]))

In [5]:
# Assign a 3-dimensional node feature vector for each node.
g.ndata["x"] = torch.randn(6, 3)
# Assign a 4-dimensional edge feature vector for each edge.
g.edata["a"] = torch.randn(5, 4)
# Assign a 5x4 node feature matrix for each node.  Node and edge features in DGL can be multi-dimensional.
g.ndata["y"] = torch.randn(6, 5, 4)

print(g.ndata["x"])

tensor([[ 0.9155, -0.8067, -0.6867],
        [ 0.0349, -0.7575, -1.0134],
        [ 0.3098, -1.4378,  0.1997],
        [ 0.0183,  0.7776, -0.4008],
        [ 1.6069,  0.5431,  0.1179],
        [-0.7951,  1.0174, -0.6450]])


## Querying graph structure

In [8]:
#performing tasks

print("Number of nodes are: {}".format(g.num_nodes()))
print("Alias of Number of nodes are: {}".format(g.number_of_nodes()))
print("Number of edges are: {}".format(g.num_edges()))
print("Alias of Number of edges are: {}".format(g.number_of_edges()))
print("Number of source nodes: {}".format(g.num_src_nodes()))
print("Alias of Number of source nodes are: {}".format(g.number_of_src_nodes()))
print("Number of destination nodes: {}".format(g.num_dst_nodes()))
print("Alias of Number of destination nodes are: {}".format(g.number_of_dst_nodes()))
print("Is g a graph uni-bipartite: {}".format(g.is_unibipartite))
print("Is g a multi graph: {}".format(g.is_multigraph))
print("Is g a homogeneous graph: {}".format(g.is_homogeneous))

Number of nodes are: 6
Alias of Number of nodes are: 6
Number of edges are: 5
Alias of Number of edges are: 5
Number of source nodes: 6
Alias of Number of source nodes are: 6
Number of destination nodes: 6
Alias of Number of destination nodes are: 6
Is g a graph uni-bipartite: False
Is g a multi graph: False
Is g a homogeneous graph: True


In [24]:
print("does g has node 4?: {}".format(g.has_nodes(4)))
print("does g has edges between 2 and 4?: {}".format(g.has_edges_between(2, 4)))
print("predecessors of node 3: {}".format(g.predecessors(3)))
print("successor(s) of node 3: {}".format(g.successors(3)))
print("edge ids given for 0 and 1?: [{}]".format(g.edge_ids(0, 1)))
print("source and destination nodes between 0,2: {}".format(g.find_edges))
print("incoming edges of node 2: {}".format(g.in_edges))
print("outgoing edges of node 2: {}".format(g.out_edges))
print("in degrees of node 2: {}".format(g.in_degrees))
print("out degrees of node 2: {}".format(g.out_degrees))

does g has node 4?: True
does g has edges between 2 and 4?: False
predecessors of node 3: tensor([0])
successor(s) of node 3: tensor([], dtype=torch.int64)
edge ids given for 0 and 1?: [0]
source and destination nodes between 0,2: <bound method DGLGraph.find_edges of Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})>
incoming edges of node 2: <bound method DGLGraph.in_edges of Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})>
outgoing edges of node 2: <bound method DGLGraph.out_edges of Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Sche

## Querying and manipulating node/edge ID type¶


In [26]:
print("type of graph data: {}".format(g.idtype))
#Cast the graph to one with idtype int64
print(g.long())
#Cast the graph to one with idtype int32
print(g.int())

type of graph data: torch.int64
Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})


## Using Node/edge features


In [37]:
print("nodes view of g: {}".format(g.nodes()))
print("data view for node features of g: {}".format(g.ndata))
print("edges view of g: {}".format(g.edges()))
print("data view for edge features of g: {}".format(g.edata))
print("g node feature schemes: {}".format(g.node_attr_schemes))
print("g edge feature schemes: {}".format(g.edge_attr_schemes))
print("node view of souce nodes at g: {}".format(g.srcnodes()))
print("node view of destination nodes at g: {}".format(g.dstnodes()))
print("data view for source node features: {}".format(g.srcdata))
print("data view for destination node features: {}".format(g.dstdata))

nodes view of g: tensor([0, 1, 2, 3, 4, 5])
data view for node features of g: {'x': tensor([[ 0.9155, -0.8067, -0.6867],
        [ 0.0349, -0.7575, -1.0134],
        [ 0.3098, -1.4378,  0.1997],
        [ 0.0183,  0.7776, -0.4008],
        [ 1.6069,  0.5431,  0.1179],
        [-0.7951,  1.0174, -0.6450]]), 'y': tensor([[[-8.6400e-01, -1.3621e+00,  1.0460e+00,  1.4120e+00],
         [-1.9421e+00, -5.4960e-01, -3.2494e-01,  4.5626e-01],
         [-1.4123e+00, -2.9757e-01,  3.3146e-01,  2.6294e+00],
         [-4.1876e-02,  1.1770e+00, -1.2094e+00, -6.0943e-01],
         [-8.8870e-01,  1.0696e+00, -3.0551e-01,  3.4084e-01]],

        [[ 1.9984e+00, -1.2550e+00, -6.4575e-01,  1.3553e+00],
         [ 2.8241e-02,  4.8059e-01, -7.8165e-02,  1.0564e+00],
         [ 4.7732e-02, -8.6159e-01,  2.2871e-01, -2.5073e-01],
         [ 3.6130e-01, -2.1704e-01,  2.4212e-01, -5.1710e-01],
         [-3.1369e-01,  1.0030e+00, -2.2104e-01, -5.1071e-01]],

        [[-1.4646e+00, -3.1892e-01, -5.9868e-01, -4.5

## Transforming graph

In [43]:
h = dgl.heterograph({
    ('user', 'plays', 'game'): ([0, 1, 1, 2], [0, 0, 2, 1]),
    ('user', 'follows', 'user'): ([0, 1, 1], [1, 2, 2])
})

In [46]:
#creating subgraphs
# Induce a subgraph from node 0, node 1 and node 3 from the original graph.
sg1 = g.subgraph([0, 1, 3])
# Induce a subgraph from edge 0, edge 1 and edge 3 from the original graph.
sg2 = g.edge_subgraph([0, 1, 3])


sh1 = h.subgraph({'user': [1, 2]})

sh2 = h.edge_subgraph({('user', 'follows', 'user'): [1, 2],
                              ('user', 'plays', 'game'): [2]})

In [48]:
sh3 = h.node_type_subgraph(['user'])
sh4 = h.edge_type_subgraph(['follows'])


In [49]:
print("sg1: {}".format(sg1))
print("sg2: {}".format(sg2))
print("sh1: {}".format(sh1))
print("sh2: {}".format(sh2))
print("sh3: {}".format(sh3))
print("sh4: {}".format(sh4))

sg1: Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)})
sg2: Graph(num_nodes=4, num_edges=3,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)})
sh1: Graph(num_nodes={'game': 0, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 0},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])
sh2: Graph(num_nodes={'game': 1, 'user': 2},
      num_edges={('user', 'follows', 'user'): 2, ('user', 'plays', 'game'): 1},
      metagraph=[('user', 'user', 'follows'), ('user', 'game

In [50]:
print(g.line_graph)

<bound method line_graph of Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})>


In [51]:
g.reverse(copy_ndata = True,copy_edata = False)

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32)}
      edata_schemes={})

In [53]:
h = h.add_self_loop(etype='follows')

In [54]:
h = h.remove_self_loop(etype='follows')

In [55]:
sg3, wm = g.to_simple(copy_ndata=False, writeback_mapping=True)
sg3

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={}
      edata_schemes={'count': Scheme(shape=(), dtype=torch.int64)})

# Part 2

## Subgraph Extraction Ops


In [60]:
g1 = dgl.graph(([0, 1, 2, 3, 4], [1, 2, 3, 4, 0]))
sg11 = dgl.node_subgraph(g, [0, 1, 4])
sg11

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32), 'y': Scheme(shape=(5, 4), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32), '_ID': Scheme(shape=(), dtype=torch.int64)})

In [61]:
sg12 = dgl.edge_subgraph(g1, [0, 4])
sg12

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [63]:
sh11 = h.node_type_subgraph(['user'])
sh11

Graph(num_nodes=3, num_edges=3,
      ndata_schemes={}
      edata_schemes={})

In [64]:
sh12 = h.edge_type_subgraph(['plays'])
sh12

Graph(num_nodes={'game': 3, 'user': 3},
      num_edges={('user', 'plays', 'game'): 4},
      metagraph=[('user', 'game', 'plays')])

In [68]:
sg13 = dgl.in_subgraph(g1, [4, 0])
sg13

Graph(num_nodes=5, num_edges=2,
      ndata_schemes={}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [69]:
sg14 = dgl.out_subgraph(g1, [4, 0], relabel_nodes=True)
sg14

Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)})

In [70]:
sg15 = dgl.khop_in_subgraph(g1, 0, k=2)
sg15

(Graph(num_nodes=3, num_edges=2,
       ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
       edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}),
 tensor([0]))

In [71]:
sg16 = dgl.khop_out_subgraph(g1, 0, k=2)
sg16

(Graph(num_nodes=3, num_edges=2,
       ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}
       edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64)}),
 tensor([0]))

# Part 3

In [76]:
# Save graphs
dgl.save_graphs("graph.dglg", g)
dgl.save_graphs("graph.dglh", h)
dgl.save_graphs("graphs.dglg", [g, sg1, sg2, sg3])
dgl.save_graphs("graphs.dglh", [h, sh1, sh2, sh3, sh4])
dgl.save_graphs("graphs.dglh1", [h, sh11, sh12])


In [78]:
# Load graphs
(g,), _ = dgl.load_graphs("graph.dglg")
(h,), _ = dgl.load_graphs("graph.dglh")

print(g)
print(h)

(g, sg1, sg2, sg3), _ = dgl.load_graphs("graphs.dglg")
print(g)
print(sg1)
print(sg2)
print(sg3)

(h, sh1, sh2, sh3, sh4), _ = dgl.load_graphs("graphs.dglh")
print(h)
print(sh1)
print(sh2)
print(sh3)
print(sh4)

(h, sh11, sh12), _ = dgl.load_graphs("graphs.dglh1")
print(h)
print(sh11)
print(sh12)

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes={'game': 3, 'user': 3},
      num_edges={('user', 'follows', 'user'): 3, ('user', 'plays', 'game'): 4},
      metagraph=[('user', 'user', 'follows'), ('user', 'game', 'plays')])
Graph(num_nodes=6, num_edges=5,
      ndata_schemes={'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=3, num_edges=2,
      ndata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'y': Scheme(shape=(5, 4), dtype=torch.float32), 'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'_ID': Scheme(shape=(), dtype=torch.int64), 'a': Scheme(shape=(4,), dtype=torch.float32)})
Graph(num_nodes=4, num_edges=3,
      ndata_schemes={'_ID': Scheme(shape=